### ISSUE TITLE
add demo

### ISSUE THREAD

**Issue by jovo** [jovo/duke-summer-alignment#10]
script that pulls data from API (or some local folder first), aligns, and reports results.  
if that already exists, make it more clear where it is.

**Comment by wrgr** [comment]
true that.

Best,
Will

On Mon, Jun 2, 2014 at 10:58 PM, joshua vogelstein <notifications@github.com

**Comment by rogerzou** [comment]
check out the improve_runtime branch. I haven't added support for the new API yet, so imageAC4 works fine. Let me know if there should be changes.

**Comment by rogerzou** [comment]
it's merged to master.
