### ISSUE TITLE
add benchmark to demo to make will happy

### ISSUE THREAD

**Issue by jovo** [jovo/duke-summer-alignment#11]
@willgray writes the below:

let's add a time benchmark to the demo so will can look at the report and make sure it fits his specs.

One other comment from me - approaches need to be scalable to be useful for our connectomics pipeline. That is, a solution that uses very slow/memory intensive feature computation may not be tractable at scale.  We've found several solutions in the literature to be unhelpful when processing large datasets.  

You guys are using AC4 for testing?  That's about 100 million voxels.  There are about 2000 of these cubes in our smallest real dataset.  So your processing on each one should finish in something like an hour max (in my opinion), and 4GB of RAM to be considered "lightweight."  There are 50,000+ such cubes in a scalable dataset with Soma.  At an hour/block, that's about two weeks on our cluster, fully loaded.  Some solutions in the literature would take over 100 years.  Really.

Also, code not written in an easy to integrate language (MATLAB > Python > Java) may be hard for us to practically use, especially if you don't fully test and provide detailed build instructions for CentOS 6.2.

**Comment by rogerzou** [comment]
running alignment on the entire imageAC4 (1024_1024_100) took 103 minutes. This includes both calculating pairwise transforms and aligning every image. Calculating the transforms takes the most time. When scaling imageAC4 by 0.5, so (512_512_100), it took 20 minutes to compute transforms, then align the original full size images. The is no significant difference in mean squared error between scaling by 0.5 and not for this data set. More tests should be done with other data sets; the user can specify how much they want to scale the image before computing the transforms for the appropriate tradeoff between running time and possible improvement in alignment quality.
